# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/hrach/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8204-DESKTOP-FSNETFU/incrSyn
set_param simulator.questaInstallPath C:/questasim64_2021.1/win64
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/Fulladder_4bit/Fulladder_4bit.cache/wt [current_project]
set_property parent.project_path D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/Fulladder_4bit/Fulladder_4bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo d:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/Fulladder_4bit/Fulladder_4bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/full_adder.v
  D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/four_bit_adder.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/Fulladder_4bit/Fulladder_4bit.srcs/constrs_1/imports/digilent-xdc/Arty-Master.xdc
set_property used_in_implementation false [get_files D:/GitHub/VTC/book_src_sch/Chapter05/HH_3005_22/Fulladder_4bit/Fulladder_4bit.srcs/constrs_1/imports/digilent-xdc/Arty-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top four_bit_adder -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef four_bit_adder.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file four_bit_adder_utilization_synth.rpt -pb four_bit_adder_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
